name: test
version: "0.1"
license: "GPL-2.0-or-later"
date: 2020-10-22
description: |
    test

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io

GAP: ">= 4.11"

www: https://mohamed-barakat.github.io/test/
readme: README.md
packageinfo: https://mohamed-barakat.github.io/test/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/mohamed-barakat/test/releases/download/v0.1/test-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar20</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>test, test,
             Version 0.1</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://mohamed-barakat.github.io/test/">https://mohamed-barakat.github.io/test/</a></span>.
    </p>
    

bibtex: |
    @misc{ test0.1,
      author =           {Barakat, M.},
      title =            {{test}, test, {V}ersion 0.1},
      month =            {Oct},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://mohamed-barakat.github.io/test/} {\texttt{https://mohamed-barakat.github.io/}\discretionary {}{}{}\texttt{test/}}},
      printedkey =       {Bar20}
    }

